pull_request_rules:
  - name: default merge rule
    conditions: []
    actions:
      merge:
        method: merge
queue_rules:
  - name: default
    conditions: []
  - name: test
scopes:
  source:
    manual:
