queue_rules:
  - name: default
    merge_conditions: []
    merge_method: merge

pull_request_rules:
  - name: add to queue automatically
    conditions:
      - base=main
    actions:
      queue:
        name: default
